[package]
name = "weectrl"
version = "0.4.0"
authors = ["Klaus Nielsen <hyperchaotic@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
slog = "1.4.1"
slog-scope = "0.2.2"
slog-stdlog = "1.1.0"
slog-stream = "1.2.0"
chrono = "0.2.25"
ssdp = "0.5.0"
time = "0.1"
hyper = "0.10.0"
serde = "0.8.22"
serde_xml = "0.9.1"
serde_json = "0.8"
serde_derive = "0.8.22"
app_dirs = "1.1.1"
url = "1.2.4"
tokio-core = "0.1.4"
futures = "0.1.10"

[dev-dependencies]
image = "0.12.2"

[dev-dependencies.conrod]
git = "https://github.com/PistonDevelopers/conrod.git"
features = ["glium", "winit"]

[lib]
name = "weectrl"
path = "src/lib.rs"

[features]
nightly = []
